// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: courses.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Palm.Courses.V1 {

  /// <summary>Holder for reflection information generated from courses.proto</summary>
  public static partial class CoursesReflection {

    #region Descriptor
    /// <summary>File descriptor for courses.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoursesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jb3Vyc2VzLnByb3RvEg9wYWxtLmNvdXJzZXMudjEyCQoHQXJ0aWNsZTIJ",
            "CgdDb21tZW50QlcKLWNvbS5naXRodWIuc2F0dXJuX3hpdi5wYWxtLnBsdWdp",
            "bnMuY291cnNlcy52MVABWiRnaXRodWIuY29tL3NhdHVybl94aXYvZmlnL2Nv",
            "dXJzZXMvdjJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
