<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nut.proto

namespace Palm\Nut\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>palm.nut.v1.GoogleProfile</code>
 */
class GoogleProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string site_verify_id = 1;</code>
     */
    protected $site_verify_id = null;
    /**
     * Generated from protobuf field <code>optional .palm.nut.v1.GoogleProfile.ReCaptcha re_captcha = 2;</code>
     */
    protected $re_captcha = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $site_verify_id
     *     @type \Palm\Nut\V1\GoogleProfile\ReCaptcha $re_captcha
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Nut::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string site_verify_id = 1;</code>
     * @return string
     */
    public function getSiteVerifyId()
    {
        return isset($this->site_verify_id) ? $this->site_verify_id : '';
    }

    public function hasSiteVerifyId()
    {
        return isset($this->site_verify_id);
    }

    public function clearSiteVerifyId()
    {
        unset($this->site_verify_id);
    }

    /**
     * Generated from protobuf field <code>optional string site_verify_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteVerifyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_verify_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .palm.nut.v1.GoogleProfile.ReCaptcha re_captcha = 2;</code>
     * @return \Palm\Nut\V1\GoogleProfile\ReCaptcha|null
     */
    public function getReCaptcha()
    {
        return $this->re_captcha;
    }

    public function hasReCaptcha()
    {
        return isset($this->re_captcha);
    }

    public function clearReCaptcha()
    {
        unset($this->re_captcha);
    }

    /**
     * Generated from protobuf field <code>optional .palm.nut.v1.GoogleProfile.ReCaptcha re_captcha = 2;</code>
     * @param \Palm\Nut\V1\GoogleProfile\ReCaptcha $var
     * @return $this
     */
    public function setReCaptcha($var)
    {
        GPBUtil::checkMessage($var, \Palm\Nut\V1\GoogleProfile\ReCaptcha::class);
        $this->re_captcha = $var;

        return $this;
    }

}

