<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nut.proto

namespace Palm\Nut\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>palm.nut.v1.SiteSmtpPingRequest</code>
 */
class SiteSmtpPingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.palm.nut.v1.EmailTask.Address to = 1;</code>
     */
    protected $to = null;
    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     */
    protected $subject = '';
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>.palm.nut.v1.SmtpProfile profile = 9;</code>
     */
    protected $profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Palm\Nut\V1\EmailTask\Address $to
     *     @type string $subject
     *     @type string $content
     *     @type \Palm\Nut\V1\SmtpProfile $profile
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Nut::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.palm.nut.v1.EmailTask.Address to = 1;</code>
     * @return \Palm\Nut\V1\EmailTask\Address|null
     */
    public function getTo()
    {
        return $this->to;
    }

    public function hasTo()
    {
        return isset($this->to);
    }

    public function clearTo()
    {
        unset($this->to);
    }

    /**
     * Generated from protobuf field <code>.palm.nut.v1.EmailTask.Address to = 1;</code>
     * @param \Palm\Nut\V1\EmailTask\Address $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkMessage($var, \Palm\Nut\V1\EmailTask\Address::class);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Generated from protobuf field <code>string subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.palm.nut.v1.SmtpProfile profile = 9;</code>
     * @return \Palm\Nut\V1\SmtpProfile|null
     */
    public function getProfile()
    {
        return $this->profile;
    }

    public function hasProfile()
    {
        return isset($this->profile);
    }

    public function clearProfile()
    {
        unset($this->profile);
    }

    /**
     * Generated from protobuf field <code>.palm.nut.v1.SmtpProfile profile = 9;</code>
     * @param \Palm\Nut\V1\SmtpProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Palm\Nut\V1\SmtpProfile::class);
        $this->profile = $var;

        return $this;
    }

}

