// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.github.saturn_xiv.palm.plugins.auth.v1;

public interface UserSignInRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.auth.v1.UserSignInRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nickname = 1;</code>
   * @return Whether the nickname field is set.
   */
  boolean hasNickname();
  /**
   * <code>string nickname = 1;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 1;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string email = 2;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 9;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 9;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   * @return Whether the ttl field is set.
   */
  boolean hasTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   * @return The ttl.
   */
  com.google.protobuf.Duration getTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   */
  com.google.protobuf.DurationOrBuilder getTtlOrBuilder();

  public com.github.saturn_xiv.palm.plugins.auth.v1.UserSignInRequest.UserCase getUserCase();
}
