[profile.release]
lto = true
strip = true

[workspace]

members = [
    "palm",
    
    "auth",
    "rbac",
    "cms",
    "forum",
    "courses",
    "mall",
    "chats",
    
    "ops/mail",
    "ops/vpn",
    "ops/metrics",
    "ops/ddns",
    
    "babel",
    "cscd",
    "cbeta",

    "coco",
]
