[profile.release]
lto = true
strip = true

[workspace]

members = [
    "palm",
    "bamboo",
    "nut",
    
    "cms",
    "forum",
    "courses",
    "mall",
    "chats",        
    "cscd",
    "cbeta",
    "flashcard",
    
    "ops/mail",
    "ops/vpn",
    "ops/metrics",
    "ops/ddns",
    "ops/router",

    "aloe",
    "coconut",
    "fig",
    "lemon",    
    "orchid",

]
