[profile.release]
lto = true

[workspace]

members = [
    "nut",
    "cbeta",
    "cscd",
    "lunar",
    "courses",
    "grocery",
    "ops/mail",
    "ops/vpn",
    "ops/metrics",
    "ops/oak",
    "loquat",

    "fig",
]
