[package]
name = "palm"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A total free education & translation & ops solution."
homepage = "https://github.com/saturn-xiv/palm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true

[features]
ubuntu = []
alpine = []
centos = []

[dependencies]
bigdecimal = "0.3"
futures = "0.3"
mime = "0.3"
language-tags = "0.3"
actix-identity = "0.4"
actix-multipart = "0.4"
log = "0.4"
num-complex = "0.4"
yaml-rust = "0.4"
toml = "0.5"
actix-cors = "0.6"
actix-files = "0.6"
tonic = "0.7"
encoding_rs = "0.8"
r2d2 = "0.8"
rand = "0.8"
xml-rs = "0.8"
env_logger = "0.9"
rusttype = "0.9"
ssh2 = "0.9"
lettre = "0.10.0-rc.6"
paho-mqtt = "0.11"
prost = "0.10"
Inflector = "0.11"
base64 = "0.13"
git2 = "0.14"
juniper = "0.15"
ipnetwork = "0.19"
nix = "0.24"
image = "0.24"
rusoto_core = "0.48"
rusoto_credential = "0.48"
rusoto_s3 = "0.48"
rusoto_sqs = "0.48"
bytes = "1"
bytesize = "1"
lazy_static = "1"
regex = "1"
serde_json = "1"
casbin = "2"
flexbuffers = "2"
humantime = "2"
lapin = "2"
percent-encoding = "2"
tempfile = "3"
handlebars = "4"
amq-protocol-uri = "7"
jsonwebtoken = "8"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.actix-session]
version = "0.6"
# git = "https://github.com/actix/actix-extras.git"
# ref = "bf41b4c"
features = ["cookie-session", "redis-rs-session"]

[dependencies.chrono-tz]
version = "0.6"
features = ["serde"]

[dependencies.uuid]
version = "1"
features = ["v4", "serde"]

[dependencies.zmq]
version = "0.9"
features = ["vendored"]

[dependencies.askama]
version = "0.11"
# features = ["with-actix-web"]
# askama_actix = "0.12"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.15"
features = ["derive", "phone", "card", "unic"]

[dependencies.cookie]
version = "0.16"
features = ["secure", "private", "percent-encode"]

[dependencies.redis]
version = "0.21"
features = ["r2d2"]

[dependencies.eui48]
version = "1"
features = ["serde_bytes"]

[dependencies.diesel]
version = "1"
default-features = false
features = ["uuidv07", "bigdecimal", "postgres", "mysql", "sqlite", "extras", "128-column-tables"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rss]
version = "2"
features = ["validation"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.actix-web]
version = "4"
features = ["cookies"]

[dependencies.openssl]
version = "*"
# features = ["vendored"]

# TODO https://github.com/image-rs/imageproc/pull/491
[dependencies.imageproc]
git = "https://github.com/image-rs/imageproc.git"
rev = "b794265"

[dependencies.diesel-adapter]
git = "https://github.com/saturn-xiv/diesel-adapter.git"
rev = "b76f84f"

[build-dependencies]
tonic-build = "0.7"
