[package]
name = "palm"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A total free education & translation & ops solution."
homepage = "https://github.com/saturn-xiv/palm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true

[dependencies]
bigdecimal = "0.3"
futures = "0.3"
mime = "0.3"
language-tags = "0.3"
actix-multipart = "0.4"
juniper_actix = "0.4"
log = "0.4"
yaml-rust = "0.4"
actix-session = "0.5"
toml = "0.5"
actix-cors = "0.6"
actix-files = "0.6"
tonic = "0.6"
encoding_rs = "0.8"
r2d2 = "0.8"
rand = "0.8"
xml-rs = "0.8"
prost = "0.9"
prost-types = "0.9"
prost-derive = "0.9"
env_logger = "0.9"
ssh2 = "0.9"
paho-mqtt = "0.10"
lettre = "0.10.0-rc.4"
Inflector = "0.11"
base64 = "0.13"
git2 = "0.14"
juniper = "0.15"
ipnetwork = "0.18"
nix = "0.23"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_s3 = "0.47"
rusoto_sqs = "0.47"
bytes = "1"
bytesize = "1"
lazy_static = "1"
regex = "1"
serde_json = "1"
flexbuffers = "2"
humantime = "2"
lapin = "2"
percent-encoding = "2"
tempfile = "3"
actix-web = "4"
handlebars = "4"
amq-protocol-uri = "7"
jsonwebtoken = "8"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.6"
features = ["serde"]

[dependencies.uuid]
version = "0.8"
features = ["v4", "serde"]

[dependencies.zmq]
version = "0.9"
features = ["vendored"]

[dependencies.askama]
version = "0.11"
# features = ["with-actix-web"]
# askama_actix = "0.12"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.14"
features = ["derive", "phone", "card", "unic"]

[dependencies.cookie]
version = "0.16"
features = ["secure", "private", "percent-encode"]

[dependencies.redis]
version = "0.21"
features = ["r2d2"]

[dependencies.eui48]
version = "1"
features = ["serde_bytes"]

[dependencies.diesel]
version = "1"
default-features = false
features = ["uuidv07", "bigdecimal", "postgres", "mysql", "sqlite", "extras", "128-column-tables"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rss]
version = "2"
features = ["validation"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.clap]
version = "3"
features = ["derive"]

[dependencies.openssl]
version = "*"
# features = ["vendored"]

