[package]
name = "palm"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A total free education & translation & ops solution."
homepage = "https://github.com/saturn-xiv/palm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = "0.3"
language-tags = "0.3"
log = "0.4"
yaml-rust = "0.4"
rocket = "0.5.0-rc.1"
serde-xml-rs = "0.5"
toml = "0.5"
tonic = "0.6"
encoding_rs = "0.8"
prost = "0.9"
prost-types = "0.9"
prost-derive = "0.9"
r2d2 = "0.8"
rand = "0.8"
xml-rs = "0.8"
env_logger = "0.9"
ssh2 = "0.9"
paho-mqtt = "0.9"
askama = "0.10"
lettre = "0.10.0-rc.3"
base64 = "0.13"
git2 = "0.13"
ipnetwork = "0.18"
nix = "0.23"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_s3 = "0.47"
rusoto_sqs = "0.47"
bytes = "1"
bytesize = "1"
lazy_static = "1"
regex = "1"
serde_json = "1"
flexbuffers = "2"
humantime = "2"
lapin = "2.0.0-beta.2"
percent-encoding = "2"
clap = "3.0.0-rc.4"
tempfile = "3"
handlebars = "4"
amq-protocol-uri = "7.0.0-beta.1"
jsonwebtoken = "7"

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
default-features = false
features = ["diesel_postgres_pool", "diesel_mysql_pool", "diesel_sqlite_pool"]

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.6"
features = ["serde"]

[dependencies.uuid]
version = "0.8"
features = ["v4", "serde"]

[dependencies.zmq]
version = "0.9"
features = ["vendored"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.14"
features = ["derive", "phone", "card", "unic"]

[dependencies.cookie]
version = "0.15"
features = ["secure", "private", "percent-encode"]

[dependencies.redis]
version = "0.21"
features = ["r2d2"]

[dependencies.eui48]
version = "1"
features = ["serde_bytes"]

[dependencies.diesel]
version = "1"
default-features = false
features = ["postgres", "mysql", "sqlite", "chrono", "serde_json", "uuid", "numeric", "r2d2", "128-column-tables"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rss]
version = "2"
features = ["validation"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.openssl]
version = "*"
features = ["vendored"]

[build-dependencies]
tonic-build = "0.6"
