CREATE TABLE IF NOT EXISTS schema_migrations(
    version BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    up LONGTEXT NOT NULL,
    down TEXT NOT NULL,
    run_on DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
