// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fig.proto

package com.github.saturn_xiv.palm.plugins.fig.v1;

public interface IndexNowProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.fig.v1.IndexNowProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
