// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fig.proto

package com.github.saturn_xiv.palm.plugins.fig.v1;

public interface ShorterLinkIndexResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.fig.v1.ShorterLinkIndexResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.palm.nut.v1.Pagination pagination = 1;</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.palm.nut.v1.Pagination pagination = 1;</code>
   * @return The pagination.
   */
  com.github.saturn_xiv.palm.plugins.nut.v1.Pagination getPagination();
  /**
   * <code>.palm.nut.v1.Pagination pagination = 1;</code>
   */
  com.github.saturn_xiv.palm.plugins.nut.v1.PaginationOrBuilder getPaginationOrBuilder();

  /**
   * <code>repeated .palm.fig.v1.ShorterLinkIndexResponse.Item items = 11;</code>
   */
  java.util.List<com.github.saturn_xiv.palm.plugins.fig.v1.ShorterLinkIndexResponse.Item> 
      getItemsList();
  /**
   * <code>repeated .palm.fig.v1.ShorterLinkIndexResponse.Item items = 11;</code>
   */
  com.github.saturn_xiv.palm.plugins.fig.v1.ShorterLinkIndexResponse.Item getItems(int index);
  /**
   * <code>repeated .palm.fig.v1.ShorterLinkIndexResponse.Item items = 11;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .palm.fig.v1.ShorterLinkIndexResponse.Item items = 11;</code>
   */
  java.util.List<? extends com.github.saturn_xiv.palm.plugins.fig.v1.ShorterLinkIndexResponse.ItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .palm.fig.v1.ShorterLinkIndexResponse.Item items = 11;</code>
   */
  com.github.saturn_xiv.palm.plugins.fig.v1.ShorterLinkIndexResponse.ItemOrBuilder getItemsOrBuilder(
      int index);
}
