use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct VoiceForm {
    #[serde(rename(deserialize = "Called"))]
    pub called: String,
    #[serde(rename(deserialize = "ToState"))]
    pub to_state: String,
    #[serde(rename(deserialize = "CallerCountry"))]
    pub caller_country: String,
    #[serde(rename(deserialize = "Direction"))]
    pub direction: String,
    #[serde(rename(deserialize = "CallerState"))]
    pub caller_state: String,
    #[serde(rename(deserialize = "ToZip"))]
    pub to_zip: String,
    #[serde(rename(deserialize = "CallSid"))]
    pub call_sid: String,
    #[serde(rename(deserialize = "To"))]
    pub to: String,
    #[serde(rename(deserialize = "CallerZip"))]
    pub caller_zip: String,
    #[serde(rename(deserialize = "ToCountry"))]
    pub to_country: String,
    #[serde(rename(deserialize = "StirVerstat"))]
    pub stir_verstat: String,
    #[serde(rename(deserialize = "ApiVersion"))]
    pub api_version: String,
    #[serde(rename(deserialize = "CalledZip"))]
    pub called_zip: String,
    #[serde(rename(deserialize = "CallStatus"))]
    pub call_status: String,
    #[serde(rename(deserialize = "CalledCity"))]
    pub called_city: String,
    #[serde(rename(deserialize = "From"))]
    pub from: String,
    #[serde(rename(deserialize = "AccountSid"))]
    pub account_sid: String,
    #[serde(rename(deserialize = "CalledCountry"))]
    pub called_country: String,
    #[serde(rename(deserialize = "CallerCity"))]
    pub caller_city: String,
    #[serde(rename(deserialize = "Caller"))]
    pub caller: String,
    #[serde(rename(deserialize = "FromCountry"))]
    pub from_country: String,
    #[serde(rename(deserialize = "ToCity"))]
    pub to_city: String,
    #[serde(rename(deserialize = "FromCity"))]
    pub from_city: String,
    #[serde(rename(deserialize = "CalledState"))]
    pub called_state: String,
    #[serde(rename(deserialize = "FromZip"))]
    pub from_zip: String,
    #[serde(rename(deserialize = "FromState"))]
    pub from_state: String,
}
