<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ops-metrics.proto

namespace Palm\Ops\Metrics\V1\ReportNginxRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>palm.ops.metrics.v1.ReportNginxRequest.Access</code>
 */
class Access extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string client_ip = 1;</code>
     */
    protected $client_ip = '';
    /**
     * Generated from protobuf field <code>string method = 2;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>string path = 3;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>float version = 4;</code>
     */
    protected $version = 0.0;
    /**
     * Generated from protobuf field <code>uint32 status = 5;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint64 body_bytes_sent = 6;</code>
     */
    protected $body_bytes_sent = 0;
    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     */
    protected $request_time = 0.0;
    /**
     * Generated from protobuf field <code>optional string http_referer = 8;</code>
     */
    protected $http_referer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $client_ip
     *     @type string $method
     *     @type string $path
     *     @type float $version
     *     @type int $status
     *     @type int|string $body_bytes_sent
     *     @type float $request_time
     *     @type string $http_referer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OpsMetrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string client_ip = 1;</code>
     * @return string
     */
    public function getClientIp()
    {
        return $this->client_ip;
    }

    /**
     * Generated from protobuf field <code>string client_ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClientIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 2;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 3;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float version = 4;</code>
     * @return float
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>float version = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkFloat($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 body_bytes_sent = 6;</code>
     * @return int|string
     */
    public function getBodyBytesSent()
    {
        return $this->body_bytes_sent;
    }

    /**
     * Generated from protobuf field <code>uint64 body_bytes_sent = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBodyBytesSent($var)
    {
        GPBUtil::checkUint64($var);
        $this->body_bytes_sent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @return float
     */
    public function getRequestTime()
    {
        return $this->request_time;
    }

    /**
     * Generated from protobuf field <code>float request_time = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setRequestTime($var)
    {
        GPBUtil::checkFloat($var);
        $this->request_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string http_referer = 8;</code>
     * @return string
     */
    public function getHttpReferer()
    {
        return isset($this->http_referer) ? $this->http_referer : '';
    }

    public function hasHttpReferer()
    {
        return isset($this->http_referer);
    }

    public function clearHttpReferer()
    {
        unset($this->http_referer);
    }

    /**
     * Generated from protobuf field <code>optional string http_referer = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHttpReferer($var)
    {
        GPBUtil::checkString($var, True);
        $this->http_referer = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Access::class, \Palm\Ops\Metrics\V1\ReportNginxRequest_Access::class);

