// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nut.proto

package com.github.saturn_xiv.palm.plugins.nut.v1;

public interface LocaleCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.nut.v1.LocaleCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lang = 1;</code>
   * @return The lang.
   */
  java.lang.String getLang();
  /**
   * <code>string lang = 1;</code>
   * @return The bytes for lang.
   */
  com.google.protobuf.ByteString
      getLangBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
