// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nut.proto

package com.github.saturn_xiv.palm.plugins.nut.v1;

public interface SignInByWechatOauth2RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.nut.v1.SignInByWechatOauth2Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string state = 1;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 1;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string app_id = 3;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 3;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>.palm.orchid.v1.WechatOauth2QrConnectRequest.Language language = 8;</code>
   * @return The enum numeric value on the wire for language.
   */
  int getLanguageValue();
  /**
   * <code>.palm.orchid.v1.WechatOauth2QrConnectRequest.Language language = 8;</code>
   * @return The language.
   */
  com.github.saturn_xiv.palm.plugins.orchid.v1.WechatOauth2QrConnectRequest.Language getLanguage();

  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   * @return Whether the ttl field is set.
   */
  boolean hasTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   * @return The ttl.
   */
  com.google.protobuf.Duration getTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 11;</code>
   */
  com.google.protobuf.DurationOrBuilder getTtlOrBuilder();
}
