- name: create downloads folder
  ansible.builtin.file:
    path: "{{ app_downloads }}"
    state: directory

- name: create backup folder
  ansible.builtin.file:
    path: "{{ app_backups }}"
    state: directory

- name: create local folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/local/"
    state: directory
