- include_tasks: init.yml
- include_tasks: sshd.yml
- include_tasks: ulimits.yml

- name: Update system
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Ubuntu'

- name: Install dependicy packages
  become: true
  apt:
    pkg:
      - pwgen
  when: ansible_distribution == 'Ubuntu'

- name: Reset root password
  become: true
  shell: echo "root:$(pwgen 32 1)" | chpasswd

- name: Reset {{ ansible_user }} password
  become: true
  shell: echo "{{ ansible_user }}:$(pwgen 32 1)" | chpasswd
  when: ansible_user != 'root'

- name: Set timezone
  become: true
  shell: timedatectl set-timezone UTC

- name: Setup journald storage
  become: true
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#Storage="
    line: Storage=persistent

# https://www.linode.com/docs/quick-answers/linux/how-to-use-journalctl/
- name: Setup journald storage keep-free
  become: true
  lineinfile:
    path: /etc/systemd/journald.conf
    state: present
    regexp: "^#SystemKeepFree="
    line: SystemKeepFree=6%
