[package]
name = "palm"
version = "2022.9.20"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tonic = "0.8"
prost = "0.11"
prost-types = "0.11"

[dependencies.diesel]
version = "2"
default-features = false
features = ["bigdecimal", "postgres", "mysql", "sqlite", "extras", "128-column-tables"]

[build-dependencies]
tonic-build = "0.8"

