<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lily.proto

namespace Palm\Lily\V1;

if (false) {
    /**
     * This class is deprecated. Use Palm\Lily\V1\ExcelModel\Sheet instead.
     * @deprecated
     */
    class ExcelModel_Sheet {}
}
class_exists(ExcelModel\Sheet::class);
@trigger_error('Palm\Lily\V1\ExcelModel_Sheet is deprecated and will be removed in the next major release. Use Palm\Lily\V1\ExcelModel\Sheet instead', E_USER_DEPRECATED);

