// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metasequoia.proto

package com.github.saturn_xiv.palm.plugins.metasequoia.v1;

public interface AttachmentShowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.metasequoia.v1.AttachmentShowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.google.protobuf.Duration ttl = 2;</code>
   * @return Whether the ttl field is set.
   */
  boolean hasTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 2;</code>
   * @return The ttl.
   */
  com.google.protobuf.Duration getTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getTtlOrBuilder();
}
