<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courses.proto

namespace GPBMetadata;

class Courses
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
˜
courses.protopalm.courses.v12	
Article2	
CommentBX
-com.github.saturn_xiv.palm.plugins.courses.v1PZ%github.com/saturn_xiv/palm/courses/v2bproto3'
        , true);

        static::$is_initialized = true;
    }
}

