// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: cbeta.proto

#include "cbeta.pb.h"
#include "cbeta.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace palm {
namespace plugins {
namespace cbeta {
namespace v1 {

std::unique_ptr< Menu::Stub> Menu::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Menu::Stub> stub(new Menu::Stub(channel, options));
  return stub;
}

Menu::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel){}

Menu::Service::Service() {
}

Menu::Service::~Service() {
}


std::unique_ptr< Book::Stub> Book::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Book::Stub> stub(new Book::Stub(channel, options));
  return stub;
}

Book::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel){}

Book::Service::Service() {
}

Book::Service::~Service() {
}


}  // namespace palm
}  // namespace plugins
}  // namespace cbeta
}  // namespace v1

