<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musa.proto

namespace Palm\Musa\V1\WechatPayFundFlowBillRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>palm.musa.v1.WechatPayFundFlowBillRequest.AccountType</code>
 */
class AccountType
{
    /**
     * Generated from protobuf enum <code>BASIC = 0;</code>
     */
    const BASIC = 0;
    /**
     * Generated from protobuf enum <code>OPERATION = 1;</code>
     */
    const OPERATION = 1;
    /**
     * Generated from protobuf enum <code>FEES = 2;</code>
     */
    const FEES = 2;

    private static $valueToName = [
        self::BASIC => 'BASIC',
        self::OPERATION => 'OPERATION',
        self::FEES => 'FEES',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AccountType::class, \Palm\Musa\V1\WechatPayFundFlowBillRequest_AccountType::class);

