[package]
name = "ops-router"
version = "2023.6.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = "0.3"
log = "0.4"
xml-rs = "0.8"
askama = "0.12"
prost = "0.12"
prost-types = "0.12"
serde_json = "1"
data-encoding = "2"
flexbuffers = "2"
tempfile = "3"
dirs = "5"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.8"
features = ["serde"]

[dependencies.rand]
version = "0.8"
features = ["alloc"]

[dependencies.tonic]
version = "0.10"
features = ["transport"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.16"
features = ["derive", "phone", "card", "unic"]

[dependencies.nix]
version = "0.27"
features = ["reboot"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.diesel]
version = "2"
default-features = false
features = ["chrono", "sqlite"]

[dependencies.ipnet]
version = "2"
features = ["serde"]

[dependencies.palm]
path = '../../palm'
