<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musa.proto

namespace Palm\Musa\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>palm.musa.v1.WechatPayFundFlowBillRequest</code>
 */
class WechatPayFundFlowBillRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayBillDate bill_date = 1;</code>
     */
    protected $bill_date = null;
    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayFundFlowBillRequest.AccountType account_type = 2;</code>
     */
    protected $account_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Palm\Musa\V1\WechatPayBillDate $bill_date
     *     @type int $account_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Musa::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayBillDate bill_date = 1;</code>
     * @return \Palm\Musa\V1\WechatPayBillDate|null
     */
    public function getBillDate()
    {
        return $this->bill_date;
    }

    public function hasBillDate()
    {
        return isset($this->bill_date);
    }

    public function clearBillDate()
    {
        unset($this->bill_date);
    }

    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayBillDate bill_date = 1;</code>
     * @param \Palm\Musa\V1\WechatPayBillDate $var
     * @return $this
     */
    public function setBillDate($var)
    {
        GPBUtil::checkMessage($var, \Palm\Musa\V1\WechatPayBillDate::class);
        $this->bill_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayFundFlowBillRequest.AccountType account_type = 2;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->account_type;
    }

    /**
     * Generated from protobuf field <code>.palm.musa.v1.WechatPayFundFlowBillRequest.AccountType account_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkEnum($var, \Palm\Musa\V1\WechatPayFundFlowBillRequest\AccountType::class);
        $this->account_type = $var;

        return $this;
    }

}

