[package]
name = "fig"
version = "2022.10.17"
edition = "2021"
description = "A crawler for palm system."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
opensearch = "2"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.clap]
version = "4"
features = ["derive"]
