[package]
name = "nut"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]
description = "A total free education & translation & ops solution."
homepage = "https://github.com/saturn-xiv/palm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
rabbitmq-stream-client = "0.1"
bigdecimal = "0.3"
futures = "0.3"
futures-util = "0.3"
mime = "0.3"
language-tags = "0.3"
actix-multipart = "0.4"
log = "0.4"
num-complex = "0.4"
yaml-rust = "0.4"
actix-identity = "0.5"
toml = "0.5"
actix-cors = "0.6"
actix-files = "0.6"
encoding_rs = "0.8"
r2d2 = "0.8"
rand = "0.8"
tonic = "0.8"
xml-rs = "0.8"
ssh2 = "0.9"
lettre = "0.10"
paho-mqtt = "0.11"
prost = "0.11"
prost-types = "0.11"
Inflector = "0.11"
base64 = "0.13"
git2 = "0.15"
aws-sdk-s3 = "0.18"
aws-sdk-sqs = "0.18"
ipnetwork = "0.20"
nix = "0.25"
aws-config = "0.48"
bytes = "1"
bytesize = "1"
lazy_static = "1"
regex = "1"
serde_json = "1"
flexbuffers = "2"
humantime = "2"
lapin = "2"
opensearch = "2"
percent-encoding = "2"
tempfile = "3"
handlebars = "4"
amq-protocol-uri = "7"
jsonwebtoken = "8"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.6"
features = ["serde"]

[dependencies.actix-session]
version = "0.7"
features = ["cookie-session", "redis-rs-session"]

[dependencies.uuid]
version = "1"
features = ["v4", "serde"]

[dependencies.zmq]
version = "0.9"
features = ["vendored"]

[dependencies.askama]
version = "0.11"
# features = ["with-actix-web"]
# askama_actix = "0.12"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.16"
features = ["derive", "phone", "card", "unic"]

[dependencies.cookie]
version = "0.16"
features = ["secure", "private", "percent-encode"]

[dependencies.redis]
version = "0.21"
features = ["r2d2"]

[dependencies.eui48]
version = "1"
features = ["serde_bytes"]

[dependencies.diesel]
version = "2"
default-features = false
features = ["bigdecimal", "postgres", "mysql", "sqlite", "extras", "128-column-tables"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.rss]
version = "2"
features = ["validation"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.actix-web]
version = "4"
features = ["cookies"]

[dependencies.openssl]
version = "*"
features = ["vendored"]

