[package]
name = "nut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
futures-util = "0.3"
language-tags = "0.3"
mime = "0.3"
actix-multipart = "0.4"
log = "0.4"
yaml-rust = "0.4"
rand = "0.8"
tonic = "0.8"
xml-rs = "0.8"
askama = "0.11"
prost = "0.11"
prost-types = "0.11"
nix = "0.25"
bytes = "1"
serde_json = "1"
flexbuffers = "2"
lapin = "2"
tempfile = "3"
handlebars = "4"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.chrono-tz]
version = "0.6"
features = ["serde"]

[dependencies.actix-session]
version = "0.7"
features = ["cookie-session", "redis-rs-session"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.validator]
version = "0.16"
features = ["derive", "phone", "card", "unic"]

[dependencies.redis]
version = "0.21"
features = ["r2d2"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.uuid]
version = "1"
features = ["v4", "serde"]

[dependencies.diesel]
version = "2"
default-features = false
features = ["bigdecimal", "postgres", "mysql", "sqlite", "extras", "128-column-tables"]

[dependencies.rss]
version = "2"
features = ["validation"]

[dependencies.actix-web]
version = "4"
features = ["cookies"]

[dependencies.openssl]
version = "*"
features = ["vendored"]

[dependencies.palm]
path = '../palm'
