<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fig.proto

namespace Palm\Fig\V1;

if (false) {
    /**
     * This class is deprecated. Use Palm\Fig\V1\SiteStatusResponse\Database instead.
     * @deprecated
     */
    class SiteStatusResponse_Database {}
}
class_exists(SiteStatusResponse\Database::class);
@trigger_error('Palm\Fig\V1\SiteStatusResponse_Database is deprecated and will be removed in the next major release. Use Palm\Fig\V1\SiteStatusResponse\Database instead', E_USER_DEPRECATED);

