[rpc]
port = 8080
max-workers = 8
ca-file = "tmp/lily/ca.crt"
cert-file = "tmp/lily/lily.crt"
key-file = "tmp/lily/lily.key"

[redis]
host = "127.0.0.1"
port = 6379
namespace = "lily"
db = 2

[rabbitmq]
host = "127.0.0.1"
port = 5672
user = "guest"
password = "guest"
virtual-host = "lily"

[minio]
endpoint = "localhost:9000"
access-key = "change-me"
secret-key = "change-me"
secure = false
namespace = "lily"
