// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ops-router.proto

package com.github.saturn_xiv.palm.plugins.ops.router.v1;

public interface RuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.ops.router.v1.Rule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>.palm.ops.router.v1.Rule.InBound in = 11;</code>
   * @return Whether the in field is set.
   */
  boolean hasIn();
  /**
   * <code>.palm.ops.router.v1.Rule.InBound in = 11;</code>
   * @return The in.
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.InBound getIn();
  /**
   * <code>.palm.ops.router.v1.Rule.InBound in = 11;</code>
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.InBoundOrBuilder getInOrBuilder();

  /**
   * <code>.palm.ops.router.v1.Rule.OutBound out = 12;</code>
   * @return Whether the out field is set.
   */
  boolean hasOut();
  /**
   * <code>.palm.ops.router.v1.Rule.OutBound out = 12;</code>
   * @return The out.
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.OutBound getOut();
  /**
   * <code>.palm.ops.router.v1.Rule.OutBound out = 12;</code>
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.OutBoundOrBuilder getOutOrBuilder();

  /**
   * <code>.palm.ops.router.v1.Rule.Nat nat = 13;</code>
   * @return Whether the nat field is set.
   */
  boolean hasNat();
  /**
   * <code>.palm.ops.router.v1.Rule.Nat nat = 13;</code>
   * @return The nat.
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.Nat getNat();
  /**
   * <code>.palm.ops.router.v1.Rule.Nat nat = 13;</code>
   */
  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.NatOrBuilder getNatOrBuilder();

  com.github.saturn_xiv.palm.plugins.ops.router.v1.Rule.PayloadCase getPayloadCase();
}
