// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cms.proto

package com.github.saturn_xiv.palm.plugins.cms.v1;

public final class Cms {
  private Cms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_cms_v1_WebSite_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_cms_v1_WebSite_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_cms_v1_NotificationIndexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_cms_v1_NotificationIndexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_cms_v1_NotificationIndexResponse_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_cms_v1_NotificationIndexResponse_Item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_cms_v1_NotificationCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_cms_v1_NotificationCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_cms_v1_NotificationUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_cms_v1_NotificationUpdateRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcms.proto\022\013palm.cms.v1\032\033google/protobu" +
      "f/empty.proto\032\037google/protobuf/timestamp" +
      ".proto\032\tnut.proto\"\035\n\007WebSite\022\022\n\ntaxonomi" +
      "es\030\t \003(\t\"\322\002\n\031NotificationIndexResponse\022:" +
      "\n\005items\030\001 \003(\0132+.palm.cms.v1.Notification" +
      "IndexResponse.Item\022+\n\npagination\030\t \001(\0132\027" +
      ".palm.nut.v1.Pagination\032\313\001\n\004Item\022\n\n\002id\030\001" +
      " \001(\005\022@\n\005level\030\002 \001(\01621.palm.cms.v1.Notifi" +
      "cationIndexResponse.Item.Level\022\r\n\005title\030" +
      "\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\014\n\004lang\030\010 \001(\t\022.\n\nupda" +
      "ted_at\030\t \001(\0132\032.google.protobuf.Timestamp" +
      "\"\033\n\005Level\022\010\n\004NOTE\020\000\022\010\n\004INFO\020\001\"\207\001\n\031Notifi" +
      "cationCreateRequest\022@\n\005level\030\001 \001(\01621.pal" +
      "m.cms.v1.NotificationIndexResponse.Item." +
      "Level\022\r\n\005title\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\014\n\004lan" +
      "g\030\t \001(\t\"\205\001\n\031NotificationUpdateRequest\022\n\n" +
      "\002id\030\001 \001(\005\022@\n\005level\030\002 \001(\01621.palm.cms.v1.N" +
      "otificationIndexResponse.Item.Level\022\r\n\005t" +
      "itle\030\003 \001(\t\022\013\n\003url\030\004 \001(\t2\371\002\n\014Notification" +
      "\022J\n\006Create\022&.palm.cms.v1.NotificationCre" +
      "ateRequest\032\026.google.protobuf.Empty\"\000\022J\n\006" +
      "Update\022&.palm.cms.v1.NotificationUpdateR" +
      "equest\032\026.google.protobuf.Empty\"\000\022E\n\005Inde" +
      "x\022\022.palm.nut.v1.Pager\032&.palm.cms.v1.Noti" +
      "ficationIndexResponse\"\000\022M\n\004Show\022\026.palm.n" +
      "ut.v1.IdRequest\032+.palm.cms.v1.Notificati" +
      "onIndexResponse.Item\"\000\022;\n\007Destory\022\026.palm" +
      ".nut.v1.IdRequest\032\026.google.protobuf.Empt" +
      "y\"\0002\010\n\006FolderB-\n)com.github.saturn_xiv.p" +
      "alm.plugins.cms.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.github.saturn_xiv.palm.plugins.nut.v1.Nut.getDescriptor(),
        });
    internal_static_palm_cms_v1_WebSite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_palm_cms_v1_WebSite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_cms_v1_WebSite_descriptor,
        new java.lang.String[] { "Taxonomies", });
    internal_static_palm_cms_v1_NotificationIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_palm_cms_v1_NotificationIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_cms_v1_NotificationIndexResponse_descriptor,
        new java.lang.String[] { "Items", "Pagination", });
    internal_static_palm_cms_v1_NotificationIndexResponse_Item_descriptor =
      internal_static_palm_cms_v1_NotificationIndexResponse_descriptor.getNestedTypes().get(0);
    internal_static_palm_cms_v1_NotificationIndexResponse_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_cms_v1_NotificationIndexResponse_Item_descriptor,
        new java.lang.String[] { "Id", "Level", "Title", "Url", "Lang", "UpdatedAt", });
    internal_static_palm_cms_v1_NotificationCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_palm_cms_v1_NotificationCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_cms_v1_NotificationCreateRequest_descriptor,
        new java.lang.String[] { "Level", "Title", "Url", "Lang", });
    internal_static_palm_cms_v1_NotificationUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_palm_cms_v1_NotificationUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_cms_v1_NotificationUpdateRequest_descriptor,
        new java.lang.String[] { "Id", "Level", "Title", "Url", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.github.saturn_xiv.palm.plugins.nut.v1.Nut.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
